config = {
    "data_path": "/kaggle/input/language-translation-englishfrench/eng_-french.csv",
    "max_vocab": 9999,
    "batch_size": 16,
    "split_size": 0.9,
    "dropout_p": 0.15,
    "max_len": 1024,
    "num_workers": 2,
    "src_tokenizer_path": "tokenizer/en_tokenizer.model",
    "tgt_tokenizer_path": "tokenizer/fr_tokenizer.model",
    "n_embed": 1024,
    "n_head": 16,
    "n_hidden": 1024 * 4,
    "n_layers": 6,
    "lr": 5e-4,
    "padding_value": 0,
    "max_epochs": 40,
    "max_data": 2**17,
    "grad_accum_steps": 4,
    "lambda_val": 5e-4
}